import Link from "next/link";
import { GlassCard } from "@/components/ui/GlassCard";
import { ArrowRight, BarChart2, ShieldCheck, Zap } from "lucide-react";

export default function Home() {
    return (
        <div className="flex flex-col min-h-screen">
            {/* Navbar */}
            <nav className="fixed top-0 w-full z-50 border-b border-white/10 bg-black/50 backdrop-blur-md">
                <div className="container mx-auto px-6 h-16 flex items-center justify-between">
                    <div className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-emerald-400 to-cyan-400">
                        AI Trade Pro
                    </div>
                    <div className="flex gap-4">
                        <Link href="/login">
                            <button className="px-4 py-2 text-sm font-medium text-gray-300 hover:text-white transition-colors">
                                Login
                            </button>
                        </Link>
                        <Link href="/login?signup=true">
                            <button className="px-4 py-2 text-sm font-medium bg-white text-black rounded-full hover:bg-gray-200 transition-colors">
                                Get Started
                            </button>
                        </Link>
                    </div>
                </div>
            </nav>

            {/* Hero Section */}
            <section className="flex-1 flex flex-col items-center justify-center pt-32 pb-20 px-6 text-center relative overflow-hidden">
                <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[800px] h-[800px] bg-emerald-500/10 rounded-full blur-[120px] -z-10" />

                <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-6 max-w-4xl">
                    Master the Markets with <br />
                    <span className="text-transparent bg-clip-text bg-gradient-to-r from-emerald-400 to-cyan-400">
                        Artificial Intelligence
                    </span>
                </h1>

                <p className="text-lg md:text-xl text-gray-400 mb-10 max-w-2xl">
                    Upload your charts, connect your API, and let our advanced AI analyze technicals, fundamentals, and news in seconds.
                </p>

                <div className="flex gap-4 mb-20">
                    <Link href="/login">
                        <button className="group relative px-8 py-4 bg-emerald-500 hover:bg-emerald-600 text-black font-bold rounded-full transition-all flex items-center gap-2">
                            Start Trading Now
                            <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
                        </button>
                    </Link>
                </div>

                {/* Features Grid */}
                <div className="grid md:grid-cols-3 gap-6 max-w-6xl w-full text-left">
                    <GlassCard className="p-8">
                        <div className="w-12 h-12 bg-emerald-500/20 rounded-lg flex items-center justify-center mb-4 text-emerald-400">
                            <BarChart2 />
                        </div>
                        <h3 className="text-xl font-bold mb-2">Technical Analysis</h3>
                        <p className="text-gray-400">Advanced pattern recognition and indicator analysis directly from your chart screenshots.</p>
                    </GlassCard>

                    <GlassCard className="p-8">
                        <div className="w-12 h-12 bg-blue-500/20 rounded-lg flex items-center justify-center mb-4 text-blue-400">
                            <Zap />
                        </div>
                        <h3 className="text-xl font-bold mb-2">Instant Signals</h3>
                        <p className="text-gray-400">Get precise Entry, Take Profit, and Stop Loss levels generated by top-tier AI models.</p>
                    </GlassCard>

                    <GlassCard className="p-8">
                        <div className="w-12 h-12 bg-purple-500/20 rounded-lg flex items-center justify-center mb-4 text-purple-400">
                            <ShieldCheck />
                        </div>
                        <h3 className="text-xl font-bold mb-2">Secure & Private</h3>
                        <p className="text-gray-400">Your API keys are stored locally. We prioritize your data privacy and security.</p>
                    </GlassCard>
                </div>
            </section>
        </div>
    );
}
